name: Deployment to GitHub Pages

on:
  push:
    branches: [develop]
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  pages: write
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: |
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            npm run build:prod
          else
            npm run build:dev
          fi

      - name: Upload Pages artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          name: 'github-pages'
          path: build

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4
        with:
          artifact-name: 'github-pages'